/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin Reset
         * @description Restore a user to seed state.
         *
         *     The fixture reset on every process restart; a real database does not, so
         *     after two rehearsals the demo account is dirty. There is no proxy route for
         *     this in the frontend, so it is unreachable from the browser by construction.
         */
        post: operations["admin_reset_admin_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask
         * @description Compose the next screen from observed behaviour.
         *
         *     SIDE-EFFECT FREE, and that is a correctness requirement rather than a
         *     preference. The frontend prefetches the other three profiles as soon as the
         *     first response lands, so this runs four times concurrently for one question.
         *
         *     Two consequences are honoured here:
         *       * the profile is NOT persisted (that is POST /profile's job alone),
         *         because four concurrent writes with four different values is
         *         last-write-wins garbage;
         *       * question selection is deterministic for a given evidence state, so all
         *         four profiles show the same question and flipping between them does not
         *         silently swap it.
         */
        post: operations["ask_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Profile
         * @description Persist the delivery preference. The ONLY writer of `profile`.
         *
         *     204 with a genuinely empty body: all three of status_code, response_class
         *     and response_model=None are required, or FastAPI documents a 200 JSON
         *     response and the contract lies about what this returns.
         */
        post: operations["set_profile_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Progress */
        get: operations["progress_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quiz/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Quiz Submit
         * @description Record an answer. The only endpoint that moves mastery.
         *
         *     Grades by `question_id` against the database. The client already holds
         *     `answer_index` for instant feedback, but the server never trusts it — the
         *     stored question is the truth.
         */
        post: operations["quiz_submit_quiz_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roadmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Roadmap */
        get: operations["roadmap_roadmap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdaptationSummary
         * @description Why this screen looks the way it does.
         *
         *     A first-class part of the response, not a string the UI assembles. The
         *     reason renders verbatim under "Why this path", and `topic_id` MUST name a
         *     topic present in the roadmap block of the same response — the UI highlights
         *     that row to show which evidence the decision rested on.
         */
        AdaptationSummary: {
            /**
             * Reason
             * @description Learner-facing. 'Back to arithmetic first — that is what linear equations depends on.'
             */
            reason: string;
            /**
             * State
             * @enum {string}
             */
            state: "worked_transfer" | "guided_practice" | "focused_practice" | "timed_drill" | "prerequisite_reset";
            /** Topic Id */
            topic_id: string;
        };
        /** ApiError */
        ApiError: {
            error: components["schemas"]["ApiErrorBody"];
        };
        /** ApiErrorBody */
        ApiErrorBody: {
            /**
             * Code
             * @description Stable, machine-readable. e.g. 'question_not_found'.
             */
            code: string;
            /**
             * Message
             * @description Learner-facing. States what happened and what to do.
             */
            message: string;
            /**
             * Retryable
             * @description Whether trying the same request again could plausibly succeed.
             */
            retryable: boolean;
        };
        /** AskRequest */
        AskRequest: {
            /**
             * Profile
             * @enum {string}
             */
            profile: "rusty" | "time_poor" | "hands_free" | "strong";
            /** Question */
            question: string;
            /** User Id */
            user_id: string;
        };
        /** AskResponse */
        AskResponse: {
            adaptation: components["schemas"]["AdaptationSummary"];
            /** Blocks */
            blocks: (components["schemas"]["ExplainerCardBlock"] | components["schemas"]["AudioExplainerBlock"] | components["schemas"]["QuizBlock"] | components["schemas"]["RoadmapBlock"] | components["schemas"]["FlashcardsBlock"] | components["schemas"]["ProgressPanelBlock"])[];
            /**
             * Cached
             * @description Dev overlay only. Never shown to a learner.
             */
            cached: boolean;
            /** Spec Id */
            spec_id: string;
        };
        /** AudioExplainerBlock */
        AudioExplainerBlock: {
            /**
             * Audio Url
             * @description Must be playable when /ask responds. The frontend never calls TTS.
             */
            audio_url: string;
            /** Duration Ms */
            duration_ms: number;
            /** Script */
            script: string;
            /** Transcript Shown */
            transcript_shown: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "audio_explainer";
        };
        /** Citation */
        Citation: {
            /** Chunk Id */
            chunk_id: string;
            /** Label */
            label: string;
        };
        /** ExplainerCardBlock */
        ExplainerCardBlock: {
            citation?: components["schemas"]["Citation"] | null;
            /** Steps */
            steps: components["schemas"]["ExplainerStep"][];
            /** Title */
            title: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "explainer_card";
        };
        /** ExplainerStep */
        ExplainerStep: {
            /**
             * Expr
             * @description TeX, marked at ingestion. The frontend never derives this from prose.
             */
            expr?: string | null;
            /**
             * Faded
             * @description Withhold this step's result and invite the learner to supply it. Backward fading: set on the LAST step only, and only when the learner has shown they can already do it.
             * @default false
             */
            faded: boolean;
            /** Text */
            text: string;
        };
        /** Flashcard */
        Flashcard: {
            /** Back */
            back: string;
            /** Front */
            front: string;
            /** Topic Id */
            topic_id: string;
        };
        /** FlashcardsBlock */
        FlashcardsBlock: {
            /** Cards */
            cards: components["schemas"]["Flashcard"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "flashcards";
        };
        /** MasteryDelta */
        MasteryDelta: {
            /** After */
            after: number;
            /** Before */
            before: number;
            /** Topic Id */
            topic_id: string;
        };
        /** ProfileRequest */
        ProfileRequest: {
            /**
             * Profile
             * @enum {string}
             */
            profile: "rusty" | "time_poor" | "hands_free" | "strong";
            /** User Id */
            user_id: string;
        };
        /** ProgressPanelBlock */
        ProgressPanelBlock: {
            /** Next Action Label */
            next_action_label: string;
            /** Streak */
            streak: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "progress_panel";
            /** Weakest Topics */
            weakest_topics: components["schemas"]["WeakTopic"][];
        };
        /** QuizBlock */
        QuizBlock: {
            /** Questions */
            questions: components["schemas"]["QuizQuestion"][];
            /**
             * Timer Seconds
             * @description Always present. Non-null for the `strong` profile only; null for every other — the key is never omitted.
             */
            timer_seconds: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "quiz";
        };
        /** QuizQuestion */
        QuizQuestion: {
            /** Answer Index */
            answer_index: number;
            /** Id */
            id: string;
            /** Options */
            options: string[];
            /** Rationale */
            rationale: string;
            /** Stem */
            stem: string;
            /**
             * Stem Expr
             * @description Always present; null when the stem carries no TeX.
             */
            stem_expr: string | null;
            /** Topic Id */
            topic_id: string;
        };
        /** QuizSubmitRequest */
        QuizSubmitRequest: {
            /**
             * Elapsed Ms
             * @description Not telemetry. The policy reads this to tell a confident answer from a laboured one, which is what separates a timed drill from guided practice.
             */
            elapsed_ms: number;
            /** Question Id */
            question_id: string;
            /** Selected Index */
            selected_index: number;
            /** Topic Id */
            topic_id: string;
            /** User Id */
            user_id: string;
        };
        /** QuizSubmitResponse */
        QuizSubmitResponse: {
            /** Answer Index */
            answer_index: number;
            /** Correct */
            correct: boolean;
            mastery: components["schemas"]["MasteryDelta"];
            /**
             * Roadmap Changed
             * @description True when ANYTHING the learner can see on the roadmap changed — ordering, status or evidence claim — not merely the ordering. The client uses this to decide whether to refetch, so a claim-only change must still report true or the screen keeps a stale row.
             */
            roadmap_changed: boolean;
        };
        /** RoadmapBlock */
        RoadmapBlock: {
            /** Steps */
            steps: components["schemas"]["RoadmapStep"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "roadmap";
        };
        /** RoadmapStep */
        RoadmapStep: {
            /**
             * Evidence Claim
             * @description Learner-facing, never a percentage. Rendered instead of mastery.
             */
            evidence_claim: string;
            /** Label */
            label: string;
            /**
             * Mastery
             * @description Ordering weight only. Never rendered — the UI shows evidence_claim.
             */
            mastery: number;
            /**
             * Status
             * @enum {string}
             */
            status: "next" | "done" | "later";
            /** Topic Id */
            topic_id: string;
        };
        /** WeakTopic */
        WeakTopic: {
            /** Evidence Claim */
            evidence_claim: string;
            /** Label */
            label: string;
            /** Mastery */
            mastery: number;
            /** Topic Id */
            topic_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    admin_reset_admin_reset_post: {
        parameters: {
            query?: {
                user_id?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    ask_ask_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    set_profile_profile_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    progress_progress_get: {
        parameters: {
            query?: {
                user_id?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressPanelBlock"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    quiz_submit_quiz_submit_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizSubmitResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    roadmap_roadmap_get: {
        parameters: {
            query?: {
                user_id?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapBlock"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
